AWSTemplateFormatVersion: '2010-09-09'
Description: 'Constraining EKS pod IAM Roles'

Parameters:
  EKSClusterName:
    Type: String
    Description: Name for EKS Cluster

  EKSOIDCURL:
    Type: String
    Description: The OpenID Connect URL (without protocol)

Resources:
  EKSPodRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Federated": "arn:aws:iam::${AWS::AccountId}:oidc-provider/${EKSOIDCURL}"
              },
              "Action": "sts:AssumeRoleWithWebIdentity",
              "Condition": {
                "StringEquals": {
                  "${EKSOIDCURL}:sub": "system:serviceaccount:test-namespace:test-service-account"
                }
              }
            }
          ]
        }
      Path: "/"
      RoleName: !Sub "${EKSClusterName}-pod-role"

Outputs:
  EKSPodRoleArn:
    Description: EKS Pod IAM Role ARN
    Value: !GetAtt EKSPodRole.Arn
